trigger:
 - none
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: "Azure Pipelines"
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
        architecture: 'x64'
    - task: CmdLine@2
      inputs:
        script: |
               python -m venv antenv
               source antenv/bin/activate
               python -m pip install --upgrade pip
               pip install setup
               pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
               python -m pip install flask
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/Application$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: deploy_uat
  jobs:
  - job: deploy_uat
    pool:
     name: "Azure Pipelines"
    steps:
    
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        itemPattern: '**/*.zip'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial (0842a7ee-3fe3-4df8-a868-313b0d4adf3a)'
        appType: 'webAppLinux'
        WebAppName: 'pythondevopsuat'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        StartupCommand: "gunicorn --bind=0.0.0.0 --workers=4 startup:app"
- stage: build_dev
  jobs:
  - job: build_Dev
    pool:
     name: "Azure Pipelines"
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: current
        downloadType: specific
        itemPattern: "**/*.zip"
        downloadPath: "$(System.ArtifactsDirectory)"
    - task: AzureRmWebAppDeployment@4
      inputs:
       ConnectionType: AzureRM
       azureSubscription: "Free Trial (0842a7ee-3fe3-4df8-a868-313b0d4adf3a)"
       WebAppName: "pythondevopsraji-dev"
       appType: webAppLinux
       packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
       StartupCommand: "gunicorn --bind=0.0.0.0 --workers=4 startup:app"
- stage: deploy_prod
  jobs:
  - job: deploy_prod
    pool:
     name: "Azure Pipelines"
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
       downloadType: specific
       buildType: current
       itemPattern: "**/*.zip"
       downloadPath: "$(System.DefaultWorkingDirectory)"
    - task: AzureRmWebAppDeployment@4
      inputs:
       ConnectionType: AzureRM
       azureSubscription: "Free Trial (0842a7ee-3fe3-4df8-a868-313b0d4adf3a)"
       appType: webAppLinux
       StartupCommand: "gunicorn --bind=0.0.0.0 --workers=4 startup:app"
       WebAppName: pythonrajidevops
       packageForLinux: "$(System.DefaultWorkingDirectory)/**/*.zip"